namespace Practice
{
    partial class FormTaskOne
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea1 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Series series1 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Title title1 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormTaskOne));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.panelButtonActivGraph = new System.Windows.Forms.Panel();
            this.buttonActiveGraph = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.panelRight = new System.Windows.Forms.Panel();
            this.panelGraph = new System.Windows.Forms.Panel();
            this.chart = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.dataResult = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.sliderDataResult = new Bunifu.UI.WinForms.BunifuHSlider();
            this.panelLeft = new System.Windows.Forms.Panel();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.buttonResult = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.resultInfo = new Bunifu.UI.WinForms.BunifuLabel();
            this.pages = new Bunifu.UI.WinForms.BunifuPages();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.label1 = new System.Windows.Forms.Label();
            this.textBoxMax = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.textBoxArgument_1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.precisionMax = new Bunifu.UI.WinForms.BunifuLabel();
            this.precisionNow = new Bunifu.UI.WinForms.BunifuLabel();
            this.precisionMin = new Bunifu.UI.WinForms.BunifuLabel();
            this.label5 = new System.Windows.Forms.Label();
            this.precisionSlider = new Bunifu.UI.WinForms.BunifuHSlider();
            this.labelArgument = new System.Windows.Forms.Label();
            this.textBoxArgument_2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuToolTip = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.bunifuSnackbar = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.panelButtonActivGraph.SuspendLayout();
            this.panelRight.SuspendLayout();
            this.panelGraph.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.chart)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataResult)).BeginInit();
            this.panelLeft.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.pages.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // panelButtonActivGraph
            // 
            this.panelButtonActivGraph.Controls.Add(this.buttonActiveGraph);
            this.panelButtonActivGraph.Dock = System.Windows.Forms.DockStyle.Right;
            this.panelButtonActivGraph.Location = new System.Drawing.Point(-50, 0);
            this.panelButtonActivGraph.Name = "panelButtonActivGraph";
            this.panelButtonActivGraph.Size = new System.Drawing.Size(50, 531);
            this.panelButtonActivGraph.TabIndex = 15;
            this.bunifuToolTip.SetToolTip(this.panelButtonActivGraph, "");
            this.bunifuToolTip.SetToolTipIcon(this.panelButtonActivGraph, null);
            this.bunifuToolTip.SetToolTipTitle(this.panelButtonActivGraph, "");
            // 
            // buttonActiveGraph
            // 
            this.buttonActiveGraph.AllowAnimations = true;
            this.buttonActiveGraph.AllowBorderColorChanges = true;
            this.buttonActiveGraph.AllowMouseEffects = true;
            this.buttonActiveGraph.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonActiveGraph.AnimationSpeed = 200;
            this.buttonActiveGraph.BackColor = System.Drawing.Color.Transparent;
            this.buttonActiveGraph.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(73)))), ((int)(((byte)(160)))), ((int)(((byte)(174)))));
            this.buttonActiveGraph.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(73)))), ((int)(((byte)(160)))), ((int)(((byte)(174)))));
            this.buttonActiveGraph.BorderRadius = 1;
            this.buttonActiveGraph.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.buttonActiveGraph.BorderThickness = 1;
            this.buttonActiveGraph.ColorContrastOnClick = 30;
            this.buttonActiveGraph.ColorContrastOnHover = 30;
            this.buttonActiveGraph.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.buttonActiveGraph.CustomizableEdges = borderEdges1;
            this.buttonActiveGraph.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonActiveGraph.Image = global::Practice.Properties.Resources.back_arrow_64px;
            this.buttonActiveGraph.ImageMargin = new System.Windows.Forms.Padding(0);
            this.buttonActiveGraph.Location = new System.Drawing.Point(0, 240);
            this.buttonActiveGraph.Name = "buttonActiveGraph";
            this.buttonActiveGraph.RoundBorders = true;
            this.buttonActiveGraph.ShowBorders = false;
            this.buttonActiveGraph.Size = new System.Drawing.Size(50, 50);
            this.buttonActiveGraph.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            this.buttonActiveGraph.TabIndex = 0;
            this.bunifuToolTip.SetToolTip(this.buttonActiveGraph, "Відкрити поле з графіком");
            this.bunifuToolTip.SetToolTipIcon(this.buttonActiveGraph, null);
            this.bunifuToolTip.SetToolTipTitle(this.buttonActiveGraph, "");
            this.buttonActiveGraph.Click += new System.EventHandler(this.ButtonActiveGraph_Click);
            // 
            // panelRight
            // 
            this.panelRight.Controls.Add(this.panelGraph);
            this.panelRight.Controls.Add(this.panelButtonActivGraph);
            this.panelRight.Dock = System.Windows.Forms.DockStyle.Right;
            this.panelRight.Location = new System.Drawing.Point(890, 5);
            this.panelRight.Name = "panelRight";
            this.panelRight.Size = new System.Drawing.Size(0, 531);
            this.panelRight.TabIndex = 16;
            this.bunifuToolTip.SetToolTip(this.panelRight, "");
            this.bunifuToolTip.SetToolTipIcon(this.panelRight, null);
            this.bunifuToolTip.SetToolTipTitle(this.panelRight, "");
            // 
            // panelGraph
            // 
            this.panelGraph.Controls.Add(this.chart);
            this.panelGraph.Controls.Add(this.dataResult);
            this.panelGraph.Controls.Add(this.sliderDataResult);
            this.panelGraph.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelGraph.Location = new System.Drawing.Point(0, 0);
            this.panelGraph.Name = "panelGraph";
            this.panelGraph.Size = new System.Drawing.Size(0, 531);
            this.panelGraph.TabIndex = 16;
            this.bunifuToolTip.SetToolTip(this.panelGraph, "");
            this.bunifuToolTip.SetToolTipIcon(this.panelGraph, null);
            this.bunifuToolTip.SetToolTipTitle(this.panelGraph, "");
            // 
            // chart
            // 
            this.chart.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.chart.BackColor = System.Drawing.Color.Gainsboro;
            chartArea1.Name = "ChartArea1";
            this.chart.ChartAreas.Add(chartArea1);
            this.chart.Location = new System.Drawing.Point(0, 0);
            this.chart.Name = "chart";
            series1.BorderWidth = 3;
            series1.ChartArea = "ChartArea1";
            series1.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Spline;
            series1.Color = System.Drawing.Color.Blue;
            series1.LegendText = " ";
            series1.Name = "Series1";
            this.chart.Series.Add(series1);
            this.chart.Size = new System.Drawing.Size(450, 420);
            this.chart.TabIndex = 18;
            this.chart.Tag = "450";
            this.chart.Text = "chart1";
            title1.BorderWidth = 2;
            title1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            title1.Name = "Title1";
            title1.Text = "Графік функцій";
            this.chart.Titles.Add(title1);
            this.bunifuToolTip.SetToolTip(this.chart, "Графік залежності значення суми від кількості підсумованих членів");
            this.bunifuToolTip.SetToolTipIcon(this.chart, null);
            this.bunifuToolTip.SetToolTipTitle(this.chart, "");
            // 
            // dataResult
            // 
            this.dataResult.AllowCustomTheming = false;
            this.dataResult.AllowUserToAddRows = false;
            this.dataResult.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dataResult.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dataResult.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.dataResult.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataResult.BackgroundColor = System.Drawing.Color.WhiteSmoke;
            this.dataResult.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataResult.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataResult.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataResult.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dataResult.ColumnHeadersHeight = 40;
            this.dataResult.ColumnHeadersVisible = false;
            this.dataResult.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dataResult.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataResult.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataResult.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataResult.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dataResult.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dataResult.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataResult.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dataResult.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dataResult.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dataResult.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dataResult.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataResult.CurrentTheme.Name = null;
            this.dataResult.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dataResult.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataResult.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataResult.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataResult.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataResult.DefaultCellStyle = dataGridViewCellStyle3;
            this.dataResult.EnableHeadersVisualStyles = false;
            this.dataResult.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataResult.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dataResult.HeaderBgColor = System.Drawing.Color.Empty;
            this.dataResult.HeaderForeColor = System.Drawing.Color.White;
            this.dataResult.Location = new System.Drawing.Point(0, 420);
            this.dataResult.Name = "dataResult";
            this.dataResult.ReadOnly = true;
            this.dataResult.RowHeadersVisible = false;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            this.dataResult.RowsDefaultCellStyle = dataGridViewCellStyle4;
            this.dataResult.RowTemplate.Height = 40;
            this.dataResult.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.dataResult.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataResult.Size = new System.Drawing.Size(450, 80);
            this.dataResult.TabIndex = 17;
            this.dataResult.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.bunifuToolTip.SetToolTip(this.dataResult, "Координати графіка");
            this.bunifuToolTip.SetToolTipIcon(this.dataResult, null);
            this.bunifuToolTip.SetToolTipTitle(this.dataResult, "");
            // 
            // sliderDataResult
            // 
            this.sliderDataResult.AllowCursorChanges = true;
            this.sliderDataResult.AllowHomeEndKeysDetection = false;
            this.sliderDataResult.AllowIncrementalClickMoves = true;
            this.sliderDataResult.AllowMouseDownEffects = false;
            this.sliderDataResult.AllowMouseHoverEffects = false;
            this.sliderDataResult.AllowScrollingAnimations = true;
            this.sliderDataResult.AllowScrollKeysDetection = true;
            this.sliderDataResult.AllowScrollOptionsMenu = true;
            this.sliderDataResult.AllowShrinkingOnFocusLost = false;
            this.sliderDataResult.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.sliderDataResult.BackColor = System.Drawing.Color.Transparent;
            this.sliderDataResult.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sliderDataResult.BackgroundImage")));
            this.sliderDataResult.BindingContainer = null;
            this.sliderDataResult.BorderRadius = 2;
            this.sliderDataResult.BorderThickness = 1;
            this.sliderDataResult.Cursor = System.Windows.Forms.Cursors.Hand;
            this.sliderDataResult.DrawThickBorder = false;
            this.sliderDataResult.DurationBeforeShrink = 2000;
            this.sliderDataResult.ElapsedColor = System.Drawing.Color.DodgerBlue;
            this.sliderDataResult.LargeChange = 1;
            this.sliderDataResult.Location = new System.Drawing.Point(0, 500);
            this.sliderDataResult.Maximum = 100;
            this.sliderDataResult.Minimum = 1;
            this.sliderDataResult.MinimumSize = new System.Drawing.Size(0, 31);
            this.sliderDataResult.MinimumThumbLength = 18;
            this.sliderDataResult.Name = "sliderDataResult";
            this.sliderDataResult.OnDisable.ScrollBarBorderColor = System.Drawing.Color.Silver;
            this.sliderDataResult.OnDisable.ScrollBarColor = System.Drawing.Color.Transparent;
            this.sliderDataResult.OnDisable.ThumbColor = System.Drawing.Color.Silver;
            this.sliderDataResult.ScrollBarBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.sliderDataResult.ScrollBarColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.sliderDataResult.ShrinkSizeLimit = 3;
            this.sliderDataResult.Size = new System.Drawing.Size(450, 31);
            this.sliderDataResult.SliderColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.sliderDataResult.SliderStyle = Bunifu.UI.WinForms.BunifuHSlider.SliderStyles.Thin;
            this.sliderDataResult.SliderThumbStyle = Utilities.BunifuSlider.BunifuHScrollBar.SliderThumbStyles.Circular;
            this.sliderDataResult.SmallChange = 1;
            this.sliderDataResult.TabIndex = 16;
            this.sliderDataResult.ThumbColor = System.Drawing.Color.DodgerBlue;
            this.sliderDataResult.ThumbFillColor = System.Drawing.SystemColors.Control;
            this.sliderDataResult.ThumbLength = 18;
            this.sliderDataResult.ThumbMargin = 1;
            this.sliderDataResult.ThumbSize = Bunifu.UI.WinForms.BunifuHSlider.ThumbSizes.Medium;
            this.sliderDataResult.ThumbStyle = Bunifu.UI.WinForms.BunifuHSlider.ThumbStyles.Outline;
            this.bunifuToolTip.SetToolTip(this.sliderDataResult, "");
            this.bunifuToolTip.SetToolTipIcon(this.sliderDataResult, null);
            this.bunifuToolTip.SetToolTipTitle(this.sliderDataResult, "");
            this.sliderDataResult.Value = 1;
            this.sliderDataResult.Scroll += new System.EventHandler<Utilities.BunifuSlider.BunifuHScrollBar.ScrollEventArgs>(this.SliderDataResult_Scroll);
            // 
            // panelLeft
            // 
            this.panelLeft.Controls.Add(this.tableLayoutPanel1);
            this.panelLeft.Controls.Add(this.pages);
            this.panelLeft.Controls.Add(this.tableLayoutPanel2);
            this.panelLeft.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelLeft.Location = new System.Drawing.Point(5, 5);
            this.panelLeft.Name = "panelLeft";
            this.panelLeft.Padding = new System.Windows.Forms.Padding(0, 0, 5, 0);
            this.panelLeft.Size = new System.Drawing.Size(885, 531);
            this.panelLeft.TabIndex = 17;
            this.bunifuToolTip.SetToolTip(this.panelLeft, "");
            this.bunifuToolTip.SetToolTipIcon(this.panelLeft, null);
            this.bunifuToolTip.SetToolTipTitle(this.panelLeft, "");
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Controls.Add(this.buttonResult, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.resultInfo, 0, 1);
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 270);
            this.tableLayoutPanel1.Margin = new System.Windows.Forms.Padding(0, 3, 0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 2;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(880, 261);
            this.tableLayoutPanel1.TabIndex = 8;
            this.bunifuToolTip.SetToolTip(this.tableLayoutPanel1, "");
            this.bunifuToolTip.SetToolTipIcon(this.tableLayoutPanel1, null);
            this.bunifuToolTip.SetToolTipTitle(this.tableLayoutPanel1, "");
            // 
            // buttonResult
            // 
            this.buttonResult.AllowAnimations = true;
            this.buttonResult.AllowMouseEffects = true;
            this.buttonResult.AllowToggling = false;
            this.buttonResult.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.buttonResult.AnimationSpeed = 200;
            this.buttonResult.AutoGenerateColors = false;
            this.buttonResult.AutoRoundBorders = false;
            this.buttonResult.AutoSizeLeftIcon = true;
            this.buttonResult.AutoSizeRightIcon = true;
            this.buttonResult.BackColor = System.Drawing.Color.Transparent;
            this.buttonResult.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.buttonResult.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonResult.BackgroundImage")));
            this.buttonResult.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonResult.ButtonText = "Результат";
            this.buttonResult.ButtonTextMarginLeft = 0;
            this.buttonResult.ColorContrastOnClick = 45;
            this.buttonResult.ColorContrastOnHover = 45;
            this.buttonResult.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.buttonResult.CustomizableEdges = borderEdges2;
            this.buttonResult.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonResult.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonResult.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonResult.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonResult.Enabled = false;
            this.buttonResult.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.buttonResult.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.buttonResult.ForeColor = System.Drawing.Color.White;
            this.buttonResult.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonResult.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonResult.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonResult.IconMarginLeft = 11;
            this.buttonResult.IconPadding = 10;
            this.buttonResult.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonResult.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonResult.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonResult.IconSize = 25;
            this.buttonResult.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.buttonResult.IdleBorderRadius = 40;
            this.buttonResult.IdleBorderThickness = 1;
            this.buttonResult.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.buttonResult.IdleIconLeftImage = null;
            this.buttonResult.IdleIconRightImage = null;
            this.buttonResult.IndicateFocus = false;
            this.buttonResult.Location = new System.Drawing.Point(385, 5);
            this.buttonResult.Name = "buttonResult";
            this.buttonResult.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonResult.OnDisabledState.BorderRadius = 40;
            this.buttonResult.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonResult.OnDisabledState.BorderThickness = 1;
            this.buttonResult.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonResult.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonResult.OnDisabledState.IconLeftImage = null;
            this.buttonResult.OnDisabledState.IconRightImage = null;
            this.buttonResult.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonResult.onHoverState.BorderRadius = 40;
            this.buttonResult.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonResult.onHoverState.BorderThickness = 1;
            this.buttonResult.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonResult.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonResult.onHoverState.IconLeftImage = null;
            this.buttonResult.onHoverState.IconRightImage = null;
            this.buttonResult.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.buttonResult.OnIdleState.BorderRadius = 40;
            this.buttonResult.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonResult.OnIdleState.BorderThickness = 1;
            this.buttonResult.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.buttonResult.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonResult.OnIdleState.IconLeftImage = null;
            this.buttonResult.OnIdleState.IconRightImage = null;
            this.buttonResult.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonResult.OnPressedState.BorderRadius = 40;
            this.buttonResult.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.buttonResult.OnPressedState.BorderThickness = 1;
            this.buttonResult.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonResult.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonResult.OnPressedState.IconLeftImage = null;
            this.buttonResult.OnPressedState.IconRightImage = null;
            this.buttonResult.Size = new System.Drawing.Size(110, 40);
            this.buttonResult.TabIndex = 6;
            this.buttonResult.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonResult.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonResult.TextMarginLeft = 0;
            this.buttonResult.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip.SetToolTip(this.buttonResult, "Натисніть, щоб отримати готовий результат");
            this.bunifuToolTip.SetToolTipIcon(this.buttonResult, null);
            this.bunifuToolTip.SetToolTipTitle(this.buttonResult, "");
            this.buttonResult.UseDefaultRadiusAndThickness = true;
            this.buttonResult.Click += new System.EventHandler(this.ButtonResult_Click);
            // 
            // resultInfo
            // 
            this.resultInfo.AllowParentOverrides = false;
            this.resultInfo.AutoEllipsis = false;
            this.resultInfo.AutoSize = false;
            this.resultInfo.Cursor = System.Windows.Forms.Cursors.Default;
            this.resultInfo.CursorType = System.Windows.Forms.Cursors.Default;
            this.resultInfo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.resultInfo.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.resultInfo.Location = new System.Drawing.Point(3, 53);
            this.resultInfo.Name = "resultInfo";
            this.resultInfo.Padding = new System.Windows.Forms.Padding(5);
            this.resultInfo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.resultInfo.Size = new System.Drawing.Size(874, 205);
            this.resultInfo.TabIndex = 7;
            this.resultInfo.Text = "Поле для виведення результату";
            this.resultInfo.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.resultInfo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip.SetToolTip(this.resultInfo, "");
            this.bunifuToolTip.SetToolTipIcon(this.resultInfo, null);
            this.bunifuToolTip.SetToolTipTitle(this.resultInfo, "");
            // 
            // pages
            // 
            this.pages.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.pages.AllowTransitions = false;
            this.pages.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.pages.Controls.Add(this.tabPage1);
            this.pages.Controls.Add(this.tabPage2);
            this.pages.Location = new System.Drawing.Point(0, 69);
            this.pages.Margin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.pages.Multiline = true;
            this.pages.Name = "pages";
            this.pages.Page = this.tabPage1;
            this.pages.PageIndex = 0;
            this.pages.PageName = "tabPage1";
            this.pages.PageTitle = "condition_1";
            this.pages.SelectedIndex = 0;
            this.pages.Size = new System.Drawing.Size(880, 201);
            this.pages.TabIndex = 7;
            this.bunifuToolTip.SetToolTip(this.pages, "");
            this.bunifuToolTip.SetToolTipIcon(this.pages, null);
            this.bunifuToolTip.SetToolTipTitle(this.pages, "");
            animation1.AnimateOnlyDifferences = false;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.pages.Transition = animation1;
            this.pages.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Custom;
            // 
            // tabPage1
            // 
            this.tabPage1.BackColor = System.Drawing.Color.WhiteSmoke;
            this.tabPage1.Controls.Add(this.label1);
            this.tabPage1.Controls.Add(this.textBoxMax);
            this.tabPage1.Controls.Add(this.label3);
            this.tabPage1.Controls.Add(this.textBoxArgument_1);
            this.tabPage1.Location = new System.Drawing.Point(4, 4);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(872, 175);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "condition_1";
            this.bunifuToolTip.SetToolTip(this.tabPage1, "");
            this.bunifuToolTip.SetToolTipIcon(this.tabPage1, null);
            this.bunifuToolTip.SetToolTipTitle(this.tabPage1, "");
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Times New Roman", 14.25F, System.Drawing.FontStyle.Bold);
            this.label1.Location = new System.Drawing.Point(222, 97);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(299, 22);
            this.label1.TabIndex = 7;
            this.label1.Text = "Введіть кількість членів від 1 до ";
            this.bunifuToolTip.SetToolTip(this.label1, "");
            this.bunifuToolTip.SetToolTipIcon(this.label1, null);
            this.bunifuToolTip.SetToolTipTitle(this.label1, "");
            // 
            // textBoxMax
            // 
            this.textBoxMax.AcceptsReturn = false;
            this.textBoxMax.AcceptsTab = false;
            this.textBoxMax.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.textBoxMax.AnimationSpeed = 200;
            this.textBoxMax.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxMax.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxMax.AutoSizeHeight = true;
            this.textBoxMax.BackColor = System.Drawing.Color.Transparent;
            this.textBoxMax.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxMax.BackgroundImage")));
            this.textBoxMax.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxMax.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxMax.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxMax.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxMax.BorderRadius = 1;
            this.textBoxMax.BorderThickness = 1;
            this.textBoxMax.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxMax.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxMax.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.textBoxMax.DefaultText = "";
            this.textBoxMax.FillColor = System.Drawing.Color.White;
            this.textBoxMax.HideSelection = true;
            this.textBoxMax.IconLeft = null;
            this.textBoxMax.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxMax.IconPadding = 10;
            this.textBoxMax.IconRight = null;
            this.textBoxMax.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxMax.Lines = new string[0];
            this.textBoxMax.Location = new System.Drawing.Point(523, 87);
            this.textBoxMax.MaxLength = 6;
            this.textBoxMax.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxMax.Modified = false;
            this.textBoxMax.Multiline = false;
            this.textBoxMax.Name = "textBoxMax";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxMax.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxMax.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxMax.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxMax.OnIdleState = stateProperties4;
            this.textBoxMax.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxMax.PasswordChar = '\0';
            this.textBoxMax.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textBoxMax.PlaceholderText = "n";
            this.textBoxMax.ReadOnly = false;
            this.textBoxMax.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxMax.SelectedText = "";
            this.textBoxMax.SelectionLength = 0;
            this.textBoxMax.SelectionStart = 0;
            this.textBoxMax.ShortcutsEnabled = true;
            this.textBoxMax.Size = new System.Drawing.Size(74, 42);
            this.textBoxMax.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textBoxMax.TabIndex = 6;
            this.textBoxMax.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxMax.TextMarginBottom = 0;
            this.textBoxMax.TextMarginLeft = 3;
            this.textBoxMax.TextMarginTop = 1;
            this.textBoxMax.TextPlaceholder = "n";
            this.bunifuToolTip.SetToolTip(this.textBoxMax, "Введіть значення кількість ітерацій циклу");
            this.bunifuToolTip.SetToolTipIcon(this.textBoxMax, null);
            this.bunifuToolTip.SetToolTipTitle(this.textBoxMax, "");
            this.textBoxMax.UseSystemPasswordChar = false;
            this.textBoxMax.WordWrap = true;
            this.textBoxMax.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.MaxLengthTextBox);
            // 
            // label3
            // 
            this.label3.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Times New Roman", 14.25F, System.Drawing.FontStyle.Bold);
            this.label3.Location = new System.Drawing.Point(291, 33);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(161, 22);
            this.label3.TabIndex = 5;
            this.label3.Text = "Введіть аргумент";
            this.bunifuToolTip.SetToolTip(this.label3, "");
            this.bunifuToolTip.SetToolTipIcon(this.label3, null);
            this.bunifuToolTip.SetToolTipTitle(this.label3, "");
            // 
            // textBoxArgument_1
            // 
            this.textBoxArgument_1.AcceptsReturn = false;
            this.textBoxArgument_1.AcceptsTab = false;
            this.textBoxArgument_1.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.textBoxArgument_1.AnimationSpeed = 200;
            this.textBoxArgument_1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxArgument_1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxArgument_1.AutoSizeHeight = true;
            this.textBoxArgument_1.BackColor = System.Drawing.Color.Transparent;
            this.textBoxArgument_1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxArgument_1.BackgroundImage")));
            this.textBoxArgument_1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxArgument_1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxArgument_1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxArgument_1.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxArgument_1.BorderRadius = 1;
            this.textBoxArgument_1.BorderThickness = 1;
            this.textBoxArgument_1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxArgument_1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxArgument_1.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.textBoxArgument_1.DefaultText = "";
            this.textBoxArgument_1.FillColor = System.Drawing.Color.White;
            this.textBoxArgument_1.HideSelection = true;
            this.textBoxArgument_1.IconLeft = null;
            this.textBoxArgument_1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxArgument_1.IconPadding = 10;
            this.textBoxArgument_1.IconRight = null;
            this.textBoxArgument_1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxArgument_1.Lines = new string[0];
            this.textBoxArgument_1.Location = new System.Drawing.Point(523, 24);
            this.textBoxArgument_1.MaxLength = 6;
            this.textBoxArgument_1.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxArgument_1.Modified = false;
            this.textBoxArgument_1.Multiline = false;
            this.textBoxArgument_1.Name = "textBoxArgument_1";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxArgument_1.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxArgument_1.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxArgument_1.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxArgument_1.OnIdleState = stateProperties8;
            this.textBoxArgument_1.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxArgument_1.PasswordChar = '\0';
            this.textBoxArgument_1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textBoxArgument_1.PlaceholderText = "x";
            this.textBoxArgument_1.ReadOnly = false;
            this.textBoxArgument_1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxArgument_1.SelectedText = "";
            this.textBoxArgument_1.SelectionLength = 0;
            this.textBoxArgument_1.SelectionStart = 0;
            this.textBoxArgument_1.ShortcutsEnabled = true;
            this.textBoxArgument_1.Size = new System.Drawing.Size(74, 42);
            this.textBoxArgument_1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textBoxArgument_1.TabIndex = 4;
            this.textBoxArgument_1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxArgument_1.TextMarginBottom = 0;
            this.textBoxArgument_1.TextMarginLeft = 3;
            this.textBoxArgument_1.TextMarginTop = 1;
            this.textBoxArgument_1.TextPlaceholder = "x";
            this.bunifuToolTip.SetToolTip(this.textBoxArgument_1, "Будь ласка, введіть аргумент для подальшого обчислення");
            this.bunifuToolTip.SetToolTipIcon(this.textBoxArgument_1, null);
            this.bunifuToolTip.SetToolTipTitle(this.textBoxArgument_1, "");
            this.textBoxArgument_1.UseSystemPasswordChar = false;
            this.textBoxArgument_1.WordWrap = true;
            this.textBoxArgument_1.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.MaxLengthTextBox);
            // 
            // tabPage2
            // 
            this.tabPage2.BackColor = System.Drawing.Color.WhiteSmoke;
            this.tabPage2.Controls.Add(this.precisionMax);
            this.tabPage2.Controls.Add(this.precisionNow);
            this.tabPage2.Controls.Add(this.precisionMin);
            this.tabPage2.Controls.Add(this.label5);
            this.tabPage2.Controls.Add(this.precisionSlider);
            this.tabPage2.Controls.Add(this.labelArgument);
            this.tabPage2.Controls.Add(this.textBoxArgument_2);
            this.tabPage2.Location = new System.Drawing.Point(4, 4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(872, 175);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "condition_2";
            this.bunifuToolTip.SetToolTip(this.tabPage2, "");
            this.bunifuToolTip.SetToolTipIcon(this.tabPage2, null);
            this.bunifuToolTip.SetToolTipTitle(this.tabPage2, "");
            // 
            // precisionMax
            // 
            this.precisionMax.AllowParentOverrides = false;
            this.precisionMax.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.precisionMax.AutoEllipsis = false;
            this.precisionMax.Cursor = System.Windows.Forms.Cursors.Default;
            this.precisionMax.CursorType = System.Windows.Forms.Cursors.Default;
            this.precisionMax.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.precisionMax.Location = new System.Drawing.Point(854, 108);
            this.precisionMax.Name = "precisionMax";
            this.precisionMax.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.precisionMax.Size = new System.Drawing.Size(8, 19);
            this.precisionMax.TabIndex = 8;
            this.precisionMax.Text = "1";
            this.precisionMax.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.precisionMax.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip.SetToolTip(this.precisionMax, "Максимальне доступне значення для порівняння точності результату");
            this.bunifuToolTip.SetToolTipIcon(this.precisionMax, null);
            this.bunifuToolTip.SetToolTipTitle(this.precisionMax, "");
            // 
            // precisionNow
            // 
            this.precisionNow.AllowParentOverrides = false;
            this.precisionNow.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.precisionNow.AutoEllipsis = false;
            this.precisionNow.Cursor = System.Windows.Forms.Cursors.Default;
            this.precisionNow.CursorType = System.Windows.Forms.Cursors.Default;
            this.precisionNow.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.precisionNow.Location = new System.Drawing.Point(424, 108);
            this.precisionNow.Name = "precisionNow";
            this.precisionNow.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.precisionNow.Size = new System.Drawing.Size(8, 19);
            this.precisionNow.TabIndex = 7;
            this.precisionNow.Text = "1";
            this.precisionNow.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.precisionNow.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip.SetToolTip(this.precisionNow, "Поточне значення для порівняння точності результату");
            this.bunifuToolTip.SetToolTipIcon(this.precisionNow, null);
            this.bunifuToolTip.SetToolTipTitle(this.precisionNow, "");
            // 
            // precisionMin
            // 
            this.precisionMin.AllowParentOverrides = false;
            this.precisionMin.AutoEllipsis = false;
            this.precisionMin.CursorType = null;
            this.precisionMin.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.precisionMin.Location = new System.Drawing.Point(10, 110);
            this.precisionMin.Name = "precisionMin";
            this.precisionMin.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.precisionMin.Size = new System.Drawing.Size(32, 19);
            this.precisionMin.TabIndex = 6;
            this.precisionMin.Text = "10<sup>-10</sup>";
            this.precisionMin.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.precisionMin.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip.SetToolTip(this.precisionMin, "Мінімальне доступне значення для порівняння точності результату");
            this.bunifuToolTip.SetToolTipIcon(this.precisionMin, null);
            this.bunifuToolTip.SetToolTipTitle(this.precisionMin, "");
            // 
            // label5
            // 
            this.label5.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label5.Font = new System.Drawing.Font("Times New Roman", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label5.Location = new System.Drawing.Point(271, 70);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(268, 23);
            this.label5.TabIndex = 4;
            this.label5.Text = "Виберіть необхідну точність";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuToolTip.SetToolTip(this.label5, "");
            this.bunifuToolTip.SetToolTipIcon(this.label5, null);
            this.bunifuToolTip.SetToolTipTitle(this.label5, "");
            // 
            // precisionSlider
            // 
            this.precisionSlider.AllowCursorChanges = true;
            this.precisionSlider.AllowHomeEndKeysDetection = false;
            this.precisionSlider.AllowIncrementalClickMoves = true;
            this.precisionSlider.AllowMouseDownEffects = false;
            this.precisionSlider.AllowMouseHoverEffects = false;
            this.precisionSlider.AllowScrollingAnimations = true;
            this.precisionSlider.AllowScrollKeysDetection = true;
            this.precisionSlider.AllowScrollOptionsMenu = true;
            this.precisionSlider.AllowShrinkingOnFocusLost = false;
            this.precisionSlider.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.precisionSlider.BackColor = System.Drawing.Color.Transparent;
            this.precisionSlider.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("precisionSlider.BackgroundImage")));
            this.precisionSlider.BindingContainer = null;
            this.precisionSlider.BorderRadius = 2;
            this.precisionSlider.BorderThickness = 1;
            this.precisionSlider.Cursor = System.Windows.Forms.Cursors.Hand;
            this.precisionSlider.DrawThickBorder = false;
            this.precisionSlider.DurationBeforeShrink = 2000;
            this.precisionSlider.ElapsedColor = System.Drawing.Color.DodgerBlue;
            this.precisionSlider.LargeChange = 1;
            this.precisionSlider.Location = new System.Drawing.Point(10, 130);
            this.precisionSlider.Maximum = 1;
            this.precisionSlider.Minimum = -9;
            this.precisionSlider.MinimumSize = new System.Drawing.Size(0, 31);
            this.precisionSlider.MinimumThumbLength = 18;
            this.precisionSlider.Name = "precisionSlider";
            this.precisionSlider.OnDisable.ScrollBarBorderColor = System.Drawing.Color.Silver;
            this.precisionSlider.OnDisable.ScrollBarColor = System.Drawing.Color.Transparent;
            this.precisionSlider.OnDisable.ThumbColor = System.Drawing.Color.Silver;
            this.precisionSlider.ScrollBarBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.precisionSlider.ScrollBarColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.precisionSlider.ShrinkSizeLimit = 3;
            this.precisionSlider.Size = new System.Drawing.Size(852, 31);
            this.precisionSlider.SliderColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.precisionSlider.SliderStyle = Bunifu.UI.WinForms.BunifuHSlider.SliderStyles.Thin;
            this.precisionSlider.SliderThumbStyle = Utilities.BunifuSlider.BunifuHScrollBar.SliderThumbStyles.Circular;
            this.precisionSlider.SmallChange = 1;
            this.precisionSlider.TabIndex = 2;
            this.precisionSlider.ThumbColor = System.Drawing.Color.DodgerBlue;
            this.precisionSlider.ThumbFillColor = System.Drawing.SystemColors.Control;
            this.precisionSlider.ThumbLength = 77;
            this.precisionSlider.ThumbMargin = 1;
            this.precisionSlider.ThumbSize = Bunifu.UI.WinForms.BunifuHSlider.ThumbSizes.Medium;
            this.precisionSlider.ThumbStyle = Bunifu.UI.WinForms.BunifuHSlider.ThumbStyles.Outline;
            this.bunifuToolTip.SetToolTip(this.precisionSlider, "Натисніть та потягніть повзунець або натисніть в біль-якій точці на ньому, щоб ви" +
        "брати необхідну точність");
            this.bunifuToolTip.SetToolTipIcon(this.precisionSlider, null);
            this.bunifuToolTip.SetToolTipTitle(this.precisionSlider, "");
            this.precisionSlider.Value = 1;
            this.precisionSlider.Scroll += new System.EventHandler<Utilities.BunifuSlider.BunifuHScrollBar.ScrollEventArgs>(this.PrecisionSlider_Scroll);
            // 
            // labelArgument
            // 
            this.labelArgument.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.labelArgument.AutoSize = true;
            this.labelArgument.Font = new System.Drawing.Font("Times New Roman", 14.25F, System.Drawing.FontStyle.Bold);
            this.labelArgument.Location = new System.Drawing.Point(285, 25);
            this.labelArgument.Name = "labelArgument";
            this.labelArgument.Size = new System.Drawing.Size(161, 22);
            this.labelArgument.TabIndex = 1;
            this.labelArgument.Text = "Введіть аргумент";
            this.bunifuToolTip.SetToolTip(this.labelArgument, "");
            this.bunifuToolTip.SetToolTipIcon(this.labelArgument, null);
            this.bunifuToolTip.SetToolTipTitle(this.labelArgument, "");
            // 
            // textBoxArgument_2
            // 
            this.textBoxArgument_2.AcceptsReturn = false;
            this.textBoxArgument_2.AcceptsTab = false;
            this.textBoxArgument_2.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.textBoxArgument_2.AnimationSpeed = 200;
            this.textBoxArgument_2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxArgument_2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxArgument_2.AutoSizeHeight = true;
            this.textBoxArgument_2.BackColor = System.Drawing.Color.Transparent;
            this.textBoxArgument_2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxArgument_2.BackgroundImage")));
            this.textBoxArgument_2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxArgument_2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxArgument_2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxArgument_2.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxArgument_2.BorderRadius = 1;
            this.textBoxArgument_2.BorderThickness = 1;
            this.textBoxArgument_2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxArgument_2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxArgument_2.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.textBoxArgument_2.DefaultText = "";
            this.textBoxArgument_2.FillColor = System.Drawing.Color.White;
            this.textBoxArgument_2.HideSelection = true;
            this.textBoxArgument_2.IconLeft = null;
            this.textBoxArgument_2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxArgument_2.IconPadding = 10;
            this.textBoxArgument_2.IconRight = null;
            this.textBoxArgument_2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxArgument_2.Lines = new string[0];
            this.textBoxArgument_2.Location = new System.Drawing.Point(479, 16);
            this.textBoxArgument_2.MaxLength = 6;
            this.textBoxArgument_2.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxArgument_2.Modified = false;
            this.textBoxArgument_2.Multiline = false;
            this.textBoxArgument_2.Name = "textBoxArgument_2";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxArgument_2.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxArgument_2.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxArgument_2.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxArgument_2.OnIdleState = stateProperties12;
            this.textBoxArgument_2.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxArgument_2.PasswordChar = '\0';
            this.textBoxArgument_2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textBoxArgument_2.PlaceholderText = "x";
            this.textBoxArgument_2.ReadOnly = false;
            this.textBoxArgument_2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxArgument_2.SelectedText = "";
            this.textBoxArgument_2.SelectionLength = 0;
            this.textBoxArgument_2.SelectionStart = 0;
            this.textBoxArgument_2.ShortcutsEnabled = true;
            this.textBoxArgument_2.Size = new System.Drawing.Size(74, 42);
            this.textBoxArgument_2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textBoxArgument_2.TabIndex = 0;
            this.textBoxArgument_2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxArgument_2.TextMarginBottom = 0;
            this.textBoxArgument_2.TextMarginLeft = 3;
            this.textBoxArgument_2.TextMarginTop = 1;
            this.textBoxArgument_2.TextPlaceholder = "x";
            this.bunifuToolTip.SetToolTip(this.textBoxArgument_2, "Будь ласка, введіть аргумент для подальшого обчислення");
            this.bunifuToolTip.SetToolTipIcon(this.textBoxArgument_2, null);
            this.bunifuToolTip.SetToolTipTitle(this.textBoxArgument_2, "");
            this.textBoxArgument_2.UseSystemPasswordChar = false;
            this.textBoxArgument_2.WordWrap = true;
            this.textBoxArgument_2.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.MaxLengthTextBox);
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel2.ColumnCount = 2;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel2.Controls.Add(this.bunifuButton22, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.bunifuButton21, 0, 0);
            this.tableLayoutPanel2.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 1;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(880, 69);
            this.tableLayoutPanel2.TabIndex = 5;
            this.bunifuToolTip.SetToolTip(this.tableLayoutPanel2, "");
            this.bunifuToolTip.SetToolTipIcon(this.tableLayoutPanel2, null);
            this.bunifuToolTip.SetToolTipTitle(this.tableLayoutPanel2, "");
            // 
            // bunifuButton22
            // 
            this.bunifuButton22.AllowAnimations = true;
            this.bunifuButton22.AllowMouseEffects = true;
            this.bunifuButton22.AllowToggling = false;
            this.bunifuButton22.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuButton22.AnimationSpeed = 200;
            this.bunifuButton22.AutoGenerateColors = false;
            this.bunifuButton22.AutoRoundBorders = false;
            this.bunifuButton22.AutoSizeLeftIcon = true;
            this.bunifuButton22.AutoSizeRightIcon = true;
            this.bunifuButton22.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.BackgroundImage")));
            this.bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.ButtonText = "Пункт №2";
            this.bunifuButton22.ButtonTextMarginLeft = 0;
            this.bunifuButton22.ColorContrastOnClick = 45;
            this.bunifuButton22.ColorContrastOnHover = 45;
            this.bunifuButton22.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton22.CustomizableEdges = borderEdges3;
            this.bunifuButton22.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton22.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton22.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bunifuButton22.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton22.IconMarginLeft = 11;
            this.bunifuButton22.IconPadding = 10;
            this.bunifuButton22.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton22.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton22.IconSize = 25;
            this.bunifuButton22.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton22.IdleBorderRadius = 40;
            this.bunifuButton22.IdleBorderThickness = 1;
            this.bunifuButton22.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton22.IdleIconLeftImage = null;
            this.bunifuButton22.IdleIconRightImage = null;
            this.bunifuButton22.IndicateFocus = false;
            this.bunifuButton22.Location = new System.Drawing.Point(614, 15);
            this.bunifuButton22.Name = "bunifuButton22";
            this.bunifuButton22.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.OnDisabledState.BorderRadius = 40;
            this.bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnDisabledState.BorderThickness = 1;
            this.bunifuButton22.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.OnDisabledState.IconLeftImage = null;
            this.bunifuButton22.OnDisabledState.IconRightImage = null;
            this.bunifuButton22.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.BorderRadius = 40;
            this.bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.onHoverState.BorderThickness = 1;
            this.bunifuButton22.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.onHoverState.IconLeftImage = null;
            this.bunifuButton22.onHoverState.IconRightImage = null;
            this.bunifuButton22.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton22.OnIdleState.BorderRadius = 40;
            this.bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnIdleState.BorderThickness = 1;
            this.bunifuButton22.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton22.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.OnIdleState.IconLeftImage = null;
            this.bunifuButton22.OnIdleState.IconRightImage = null;
            this.bunifuButton22.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.BorderRadius = 40;
            this.bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnPressedState.BorderThickness = 1;
            this.bunifuButton22.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.OnPressedState.IconLeftImage = null;
            this.bunifuButton22.OnPressedState.IconRightImage = null;
            this.bunifuButton22.Size = new System.Drawing.Size(91, 39);
            this.bunifuButton22.TabIndex = 4;
            this.bunifuButton22.Tag = "condition_2";
            this.bunifuButton22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton22.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton22.TextMarginLeft = 0;
            this.bunifuButton22.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip.SetToolTip(this.bunifuButton22, "Перейти до виконання пункту 2 завдання №1");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButton22, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButton22, "");
            this.bunifuButton22.UseDefaultRadiusAndThickness = true;
            this.bunifuButton22.Click += new System.EventHandler(this.SelectPage);
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Пункт №1";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges4;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.IdleBorderRadius = 40;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(174, 15);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 40;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.BorderRadius = 40;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.OnIdleState.BorderRadius = 40;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 40;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(91, 39);
            this.bunifuButton21.TabIndex = 3;
            this.bunifuButton21.Tag = "condition_1";
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip.SetToolTip(this.bunifuButton21, "Перейти до виконання пункту 1 завдання №1");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButton21, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButton21, "");
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.Click += new System.EventHandler(this.SelectPage);
            // 
            // bunifuToolTip
            // 
            this.bunifuToolTip.Active = true;
            this.bunifuToolTip.AlignTextWithTitle = false;
            this.bunifuToolTip.AllowAutoClose = false;
            this.bunifuToolTip.AllowFading = true;
            this.bunifuToolTip.AutoCloseDuration = 5000;
            this.bunifuToolTip.BackColor = System.Drawing.SystemColors.Control;
            this.bunifuToolTip.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuToolTip.ClickToShowDisplayControl = false;
            this.bunifuToolTip.ConvertNewlinesToBreakTags = true;
            this.bunifuToolTip.DisplayControl = null;
            this.bunifuToolTip.EntryAnimationSpeed = 350;
            this.bunifuToolTip.ExitAnimationSpeed = 200;
            this.bunifuToolTip.GenerateAutoCloseDuration = false;
            this.bunifuToolTip.IconMargin = 6;
            this.bunifuToolTip.InitialDelay = 0;
            this.bunifuToolTip.Name = "bunifuToolTip";
            this.bunifuToolTip.Opacity = 1D;
            this.bunifuToolTip.OverrideToolTipTitles = false;
            this.bunifuToolTip.Padding = new System.Windows.Forms.Padding(10);
            this.bunifuToolTip.ReshowDelay = 100;
            this.bunifuToolTip.ShowAlways = true;
            this.bunifuToolTip.ShowBorders = false;
            this.bunifuToolTip.ShowIcons = true;
            this.bunifuToolTip.ShowShadows = true;
            this.bunifuToolTip.Tag = null;
            this.bunifuToolTip.TextFont = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuToolTip.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuToolTip.TextMargin = 2;
            this.bunifuToolTip.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.bunifuToolTip.TitleForeColor = System.Drawing.Color.Black;
            this.bunifuToolTip.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.bunifuToolTip.ToolTipTitle = null;
            // 
            // bunifuSnackbar
            // 
            this.bunifuSnackbar.AllowDragging = false;
            this.bunifuSnackbar.AllowMultipleViews = true;
            this.bunifuSnackbar.ClickToClose = true;
            this.bunifuSnackbar.DoubleClickToClose = true;
            this.bunifuSnackbar.DurationAfterIdle = 3000;
            this.bunifuSnackbar.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar.FadeCloseIcon = false;
            this.bunifuSnackbar.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar.Margin = 10;
            this.bunifuSnackbar.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar.MaximumViews = 7;
            this.bunifuSnackbar.MessageRightMargin = 15;
            this.bunifuSnackbar.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar.ShowBorders = false;
            this.bunifuSnackbar.ShowCloseIcon = false;
            this.bunifuSnackbar.ShowIcon = true;
            this.bunifuSnackbar.ShowShadows = true;
            this.bunifuSnackbar.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar.ViewsMargin = 7;
            this.bunifuSnackbar.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar.ZoomCloseIcon = true;
            // 
            // FormTaskOne
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.WhiteSmoke;
            this.ClientSize = new System.Drawing.Size(895, 541);
            this.Controls.Add(this.panelLeft);
            this.Controls.Add(this.panelRight);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormTaskOne";
            this.Padding = new System.Windows.Forms.Padding(5);
            this.Tag = "1040";
            this.Text = "Завдання №1";
            this.panelButtonActivGraph.ResumeLayout(false);
            this.panelRight.ResumeLayout(false);
            this.panelGraph.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.chart)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataResult)).EndInit();
            this.panelLeft.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.pages.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.tableLayoutPanel2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Panel panelButtonActivGraph;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton buttonActiveGraph;
        private System.Windows.Forms.Panel panelRight;
        private System.Windows.Forms.Panel panelGraph;
        private System.Windows.Forms.DataVisualization.Charting.Chart chart;
        private Bunifu.UI.WinForms.BunifuDataGridView dataResult;
        private Bunifu.UI.WinForms.BunifuHSlider sliderDataResult;
        private System.Windows.Forms.Panel panelLeft;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 buttonResult;
        private Bunifu.UI.WinForms.BunifuLabel resultInfo;
        private Bunifu.UI.WinForms.BunifuPages pages;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxMax;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxArgument_1;
        private System.Windows.Forms.TabPage tabPage2;
        private Bunifu.UI.WinForms.BunifuLabel precisionMax;
        private Bunifu.UI.WinForms.BunifuLabel precisionNow;
        private Bunifu.UI.WinForms.BunifuLabel precisionMin;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuHSlider precisionSlider;
        private System.Windows.Forms.Label labelArgument;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxArgument_2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuToolTip bunifuToolTip;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar;
    }
}