namespace Practice
{
    partial class UserProfile
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UserProfile));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.formDock = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuToolTip = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.bunifuGradientPanelDesktop = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuGradientPanelTitleBar = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuButtonMaximize = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.iconCurrentChildForm = new Bunifu.UI.WinForms.BunifuImageButton();
            this.labelCurrentChildForm = new System.Windows.Forms.Label();
            this.bunifuButtonMinimized = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButtonClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGradientPanelMenu = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.panelLogo = new System.Windows.Forms.Panel();
            this.bunifuButtonMenu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButtonTaskOne = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButtonTaskFive = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButtonTaskTwo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButtonTaskFour = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButtonTaskThree = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuGradientPanelTitleBar.SuspendLayout();
            this.bunifuGradientPanelMenu.SuspendLayout();
            this.panelLogo.SuspendLayout();
            this.SuspendLayout();
            // 
            // formDock
            // 
            this.formDock.AllowFormDragging = true;
            this.formDock.AllowFormDropShadow = true;
            this.formDock.AllowFormResizing = true;
            this.formDock.AllowHidingBottomRegion = true;
            this.formDock.AllowOpacityChangesWhileDragging = false;
            this.formDock.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.formDock.BorderOptions.BottomBorder.BorderThickness = 1;
            this.formDock.BorderOptions.BottomBorder.ShowBorder = true;
            this.formDock.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.formDock.BorderOptions.LeftBorder.BorderThickness = 1;
            this.formDock.BorderOptions.LeftBorder.ShowBorder = true;
            this.formDock.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.formDock.BorderOptions.RightBorder.BorderThickness = 1;
            this.formDock.BorderOptions.RightBorder.ShowBorder = true;
            this.formDock.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.formDock.BorderOptions.TopBorder.BorderThickness = 1;
            this.formDock.BorderOptions.TopBorder.ShowBorder = true;
            this.formDock.ContainerControl = this;
            this.formDock.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.formDock.DockingIndicatorsOpacity = 0.5D;
            this.formDock.DockingOptions.DockAll = true;
            this.formDock.DockingOptions.DockBottomLeft = true;
            this.formDock.DockingOptions.DockBottomRight = true;
            this.formDock.DockingOptions.DockFullScreen = true;
            this.formDock.DockingOptions.DockLeft = true;
            this.formDock.DockingOptions.DockRight = true;
            this.formDock.DockingOptions.DockTopLeft = true;
            this.formDock.DockingOptions.DockTopRight = true;
            this.formDock.FormDraggingOpacity = 0.9D;
            this.formDock.ParentForm = this;
            this.formDock.ShowCursorChanges = true;
            this.formDock.ShowDockingIndicators = true;
            this.formDock.TitleBarOptions.AllowFormDragging = true;
            this.formDock.TitleBarOptions.BunifuFormDock = this.formDock;
            this.formDock.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.formDock.TitleBarOptions.TitleBarControl = this.bunifuGradientPanelTitleBar;
            this.formDock.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bunifuToolTip
            // 
            this.bunifuToolTip.Active = true;
            this.bunifuToolTip.AlignTextWithTitle = false;
            this.bunifuToolTip.AllowAutoClose = false;
            this.bunifuToolTip.AllowFading = true;
            this.bunifuToolTip.AutoCloseDuration = 5000;
            this.bunifuToolTip.BackColor = System.Drawing.SystemColors.Control;
            this.bunifuToolTip.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuToolTip.ClickToShowDisplayControl = false;
            this.bunifuToolTip.ConvertNewlinesToBreakTags = true;
            this.bunifuToolTip.DisplayControl = null;
            this.bunifuToolTip.EntryAnimationSpeed = 350;
            this.bunifuToolTip.ExitAnimationSpeed = 200;
            this.bunifuToolTip.GenerateAutoCloseDuration = false;
            this.bunifuToolTip.IconMargin = 6;
            this.bunifuToolTip.InitialDelay = 0;
            this.bunifuToolTip.Name = "bunifuToolTip";
            this.bunifuToolTip.Opacity = 1D;
            this.bunifuToolTip.OverrideToolTipTitles = false;
            this.bunifuToolTip.Padding = new System.Windows.Forms.Padding(10);
            this.bunifuToolTip.ReshowDelay = 100;
            this.bunifuToolTip.ShowAlways = true;
            this.bunifuToolTip.ShowBorders = false;
            this.bunifuToolTip.ShowIcons = true;
            this.bunifuToolTip.ShowShadows = true;
            this.bunifuToolTip.Tag = null;
            this.bunifuToolTip.TextFont = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuToolTip.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuToolTip.TextMargin = 2;
            this.bunifuToolTip.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.bunifuToolTip.TitleForeColor = System.Drawing.Color.Black;
            this.bunifuToolTip.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.bunifuToolTip.ToolTipTitle = null;
            // 
            // bunifuGradientPanelDesktop
            // 
            this.bunifuGradientPanelDesktop.AutoScroll = true;
            this.bunifuGradientPanelDesktop.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanelDesktop.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanelDesktop.BackgroundImage")));
            this.bunifuGradientPanelDesktop.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanelDesktop.BorderRadius = 1;
            this.bunifuGradientPanelDesktop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGradientPanelDesktop.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuGradientPanelDesktop.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuGradientPanelDesktop.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuGradientPanelDesktop.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuGradientPanelDesktop.Location = new System.Drawing.Point(222, 64);
            this.bunifuGradientPanelDesktop.Margin = new System.Windows.Forms.Padding(0, 0, 0, 3);
            this.bunifuGradientPanelDesktop.Name = "bunifuGradientPanelDesktop";
            this.bunifuGradientPanelDesktop.Quality = 10;
            this.bunifuGradientPanelDesktop.Size = new System.Drawing.Size(893, 553);
            this.bunifuGradientPanelDesktop.TabIndex = 38;
            this.bunifuToolTip.SetToolTip(this.bunifuGradientPanelDesktop, "");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuGradientPanelDesktop, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuGradientPanelDesktop, "");
            // 
            // bunifuGradientPanelTitleBar
            // 
            this.bunifuGradientPanelTitleBar.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanelTitleBar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanelTitleBar.BackgroundImage")));
            this.bunifuGradientPanelTitleBar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanelTitleBar.BorderRadius = 0;
            this.bunifuGradientPanelTitleBar.Controls.Add(this.bunifuButtonMaximize);
            this.bunifuGradientPanelTitleBar.Controls.Add(this.iconCurrentChildForm);
            this.bunifuGradientPanelTitleBar.Controls.Add(this.labelCurrentChildForm);
            this.bunifuGradientPanelTitleBar.Controls.Add(this.bunifuButtonMinimized);
            this.bunifuGradientPanelTitleBar.Controls.Add(this.bunifuButtonClose);
            this.bunifuGradientPanelTitleBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuGradientPanelTitleBar.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuGradientPanelTitleBar.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuGradientPanelTitleBar.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuGradientPanelTitleBar.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuGradientPanelTitleBar.Location = new System.Drawing.Point(222, 2);
            this.bunifuGradientPanelTitleBar.Name = "bunifuGradientPanelTitleBar";
            this.bunifuGradientPanelTitleBar.Quality = 10;
            this.bunifuGradientPanelTitleBar.Size = new System.Drawing.Size(893, 62);
            this.bunifuGradientPanelTitleBar.TabIndex = 34;
            this.bunifuToolTip.SetToolTip(this.bunifuGradientPanelTitleBar, "");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuGradientPanelTitleBar, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuGradientPanelTitleBar, "");
            // 
            // bunifuButtonMaximize
            // 
            this.bunifuButtonMaximize.AllowAnimations = true;
            this.bunifuButtonMaximize.AllowMouseEffects = true;
            this.bunifuButtonMaximize.AllowToggling = false;
            this.bunifuButtonMaximize.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButtonMaximize.AnimationSpeed = 200;
            this.bunifuButtonMaximize.AutoGenerateColors = false;
            this.bunifuButtonMaximize.AutoRoundBorders = false;
            this.bunifuButtonMaximize.AutoSizeLeftIcon = true;
            this.bunifuButtonMaximize.AutoSizeRightIcon = true;
            this.bunifuButtonMaximize.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMaximize.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButtonMaximize.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonMaximize.BackgroundImage")));
            this.bunifuButtonMaximize.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMaximize.ButtonText = "";
            this.bunifuButtonMaximize.ButtonTextMarginLeft = 0;
            this.bunifuButtonMaximize.ColorContrastOnClick = 45;
            this.bunifuButtonMaximize.ColorContrastOnHover = 45;
            this.bunifuButtonMaximize.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButtonMaximize.CustomizableEdges = borderEdges1;
            this.bunifuButtonMaximize.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonMaximize.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMaximize.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButtonMaximize.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButtonMaximize.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonMaximize.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButtonMaximize.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMaximize.IconLeft = null;
            this.bunifuButtonMaximize.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonMaximize.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonMaximize.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonMaximize.IconMarginLeft = 11;
            this.bunifuButtonMaximize.IconPadding = 10;
            this.bunifuButtonMaximize.IconRight = global::Practice.Properties.Resources.full_screen_32px;
            this.bunifuButtonMaximize.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonMaximize.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonMaximize.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonMaximize.IconSize = 26;
            this.bunifuButtonMaximize.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButtonMaximize.IdleBorderRadius = 0;
            this.bunifuButtonMaximize.IdleBorderThickness = 0;
            this.bunifuButtonMaximize.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButtonMaximize.IdleIconLeftImage = null;
            this.bunifuButtonMaximize.IdleIconRightImage = global::Practice.Properties.Resources.full_screen_32px;
            this.bunifuButtonMaximize.IndicateFocus = true;
            this.bunifuButtonMaximize.Location = new System.Drawing.Point(827, 0);
            this.bunifuButtonMaximize.Name = "bunifuButtonMaximize";
            this.bunifuButtonMaximize.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMaximize.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonMaximize.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMaximize.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonMaximize.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMaximize.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMaximize.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonMaximize.OnDisabledState.IconRightImage = null;
            this.bunifuButtonMaximize.onHoverState.BorderColor = System.Drawing.Color.Blue;
            this.bunifuButtonMaximize.onHoverState.BorderRadius = 1;
            this.bunifuButtonMaximize.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMaximize.onHoverState.BorderThickness = 1;
            this.bunifuButtonMaximize.onHoverState.FillColor = System.Drawing.Color.Blue;
            this.bunifuButtonMaximize.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMaximize.onHoverState.IconLeftImage = null;
            this.bunifuButtonMaximize.onHoverState.IconRightImage = null;
            this.bunifuButtonMaximize.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMaximize.OnIdleState.BorderRadius = 1;
            this.bunifuButtonMaximize.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMaximize.OnIdleState.BorderThickness = 1;
            this.bunifuButtonMaximize.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMaximize.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMaximize.OnIdleState.IconLeftImage = null;
            this.bunifuButtonMaximize.OnIdleState.IconRightImage = global::Practice.Properties.Resources.full_screen_32px;
            this.bunifuButtonMaximize.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(102)))), ((int)(((byte)(204)))));
            this.bunifuButtonMaximize.OnPressedState.BorderRadius = 1;
            this.bunifuButtonMaximize.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMaximize.OnPressedState.BorderThickness = 1;
            this.bunifuButtonMaximize.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(102)))), ((int)(((byte)(204)))));
            this.bunifuButtonMaximize.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMaximize.OnPressedState.IconLeftImage = null;
            this.bunifuButtonMaximize.OnPressedState.IconRightImage = null;
            this.bunifuButtonMaximize.Size = new System.Drawing.Size(33, 40);
            this.bunifuButtonMaximize.TabIndex = 32;
            this.bunifuButtonMaximize.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonMaximize.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonMaximize.TextMarginLeft = 0;
            this.bunifuButtonMaximize.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonMaximize, "Розгорнути на увесь екран");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonMaximize, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonMaximize, "");
            this.bunifuButtonMaximize.UseDefaultRadiusAndThickness = true;
            // 
            // iconCurrentChildForm
            // 
            this.iconCurrentChildForm.ActiveImage = null;
            this.iconCurrentChildForm.AllowAnimations = true;
            this.iconCurrentChildForm.AllowBuffering = true;
            this.iconCurrentChildForm.AllowToggling = false;
            this.iconCurrentChildForm.AllowZooming = true;
            this.iconCurrentChildForm.AllowZoomingOnFocus = false;
            this.iconCurrentChildForm.BackColor = System.Drawing.Color.Transparent;
            this.iconCurrentChildForm.DialogResult = System.Windows.Forms.DialogResult.None;
            this.iconCurrentChildForm.ErrorImage = null;
            this.iconCurrentChildForm.FadeWhenInactive = false;
            this.iconCurrentChildForm.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.iconCurrentChildForm.Image = null;
            this.iconCurrentChildForm.ImageActive = null;
            this.iconCurrentChildForm.ImageLocation = null;
            this.iconCurrentChildForm.ImageMargin = 20;
            this.iconCurrentChildForm.ImageSize = new System.Drawing.Size(30, 30);
            this.iconCurrentChildForm.ImageZoomSize = new System.Drawing.Size(50, 50);
            this.iconCurrentChildForm.InitialImage = null;
            this.iconCurrentChildForm.Location = new System.Drawing.Point(10, 10);
            this.iconCurrentChildForm.Name = "iconCurrentChildForm";
            this.iconCurrentChildForm.Rotation = 0;
            this.iconCurrentChildForm.ShowActiveImage = true;
            this.iconCurrentChildForm.ShowCursorChanges = true;
            this.iconCurrentChildForm.ShowImageBorders = false;
            this.iconCurrentChildForm.ShowSizeMarkers = false;
            this.iconCurrentChildForm.Size = new System.Drawing.Size(50, 50);
            this.iconCurrentChildForm.TabIndex = 34;
            this.bunifuToolTip.SetToolTip(this.iconCurrentChildForm, "");
            this.bunifuToolTip.SetToolTipIcon(this.iconCurrentChildForm, null);
            this.iconCurrentChildForm.ToolTipText = "";
            this.bunifuToolTip.SetToolTipTitle(this.iconCurrentChildForm, "");
            this.iconCurrentChildForm.WaitOnLoad = false;
            this.iconCurrentChildForm.Zoom = 20;
            this.iconCurrentChildForm.ZoomSpeed = 10;
            // 
            // labelCurrentChildForm
            // 
            this.labelCurrentChildForm.AutoSize = true;
            this.labelCurrentChildForm.Font = new System.Drawing.Font("Times New Roman", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.labelCurrentChildForm.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.labelCurrentChildForm.Location = new System.Drawing.Point(71, 25);
            this.labelCurrentChildForm.Name = "labelCurrentChildForm";
            this.labelCurrentChildForm.Size = new System.Drawing.Size(126, 22);
            this.labelCurrentChildForm.TabIndex = 1;
            this.labelCurrentChildForm.Text = "Завдання №5";
            this.labelCurrentChildForm.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuToolTip.SetToolTip(this.labelCurrentChildForm, "");
            this.bunifuToolTip.SetToolTipIcon(this.labelCurrentChildForm, null);
            this.bunifuToolTip.SetToolTipTitle(this.labelCurrentChildForm, "");
            // 
            // bunifuButtonMinimized
            // 
            this.bunifuButtonMinimized.AllowAnimations = true;
            this.bunifuButtonMinimized.AllowMouseEffects = true;
            this.bunifuButtonMinimized.AllowToggling = false;
            this.bunifuButtonMinimized.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButtonMinimized.AnimationSpeed = 200;
            this.bunifuButtonMinimized.AutoGenerateColors = false;
            this.bunifuButtonMinimized.AutoRoundBorders = false;
            this.bunifuButtonMinimized.AutoSizeLeftIcon = true;
            this.bunifuButtonMinimized.AutoSizeRightIcon = true;
            this.bunifuButtonMinimized.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMinimized.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButtonMinimized.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonMinimized.BackgroundImage")));
            this.bunifuButtonMinimized.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMinimized.ButtonText = "";
            this.bunifuButtonMinimized.ButtonTextMarginLeft = 0;
            this.bunifuButtonMinimized.ColorContrastOnClick = 45;
            this.bunifuButtonMinimized.ColorContrastOnHover = 45;
            this.bunifuButtonMinimized.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButtonMinimized.CustomizableEdges = borderEdges2;
            this.bunifuButtonMinimized.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonMinimized.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMinimized.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButtonMinimized.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButtonMinimized.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonMinimized.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButtonMinimized.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMinimized.IconLeft = null;
            this.bunifuButtonMinimized.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonMinimized.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonMinimized.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonMinimized.IconMarginLeft = 11;
            this.bunifuButtonMinimized.IconPadding = 10;
            this.bunifuButtonMinimized.IconRight = global::Practice.Properties.Resources.minimise_32px;
            this.bunifuButtonMinimized.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonMinimized.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonMinimized.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonMinimized.IconSize = 26;
            this.bunifuButtonMinimized.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButtonMinimized.IdleBorderRadius = 0;
            this.bunifuButtonMinimized.IdleBorderThickness = 0;
            this.bunifuButtonMinimized.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButtonMinimized.IdleIconLeftImage = null;
            this.bunifuButtonMinimized.IdleIconRightImage = global::Practice.Properties.Resources.minimise_32px;
            this.bunifuButtonMinimized.IndicateFocus = true;
            this.bunifuButtonMinimized.Location = new System.Drawing.Point(791, 0);
            this.bunifuButtonMinimized.Name = "bunifuButtonMinimized";
            this.bunifuButtonMinimized.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMinimized.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonMinimized.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMinimized.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonMinimized.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMinimized.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMinimized.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonMinimized.OnDisabledState.IconRightImage = null;
            this.bunifuButtonMinimized.onHoverState.BorderColor = System.Drawing.Color.Blue;
            this.bunifuButtonMinimized.onHoverState.BorderRadius = 1;
            this.bunifuButtonMinimized.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMinimized.onHoverState.BorderThickness = 1;
            this.bunifuButtonMinimized.onHoverState.FillColor = System.Drawing.Color.Blue;
            this.bunifuButtonMinimized.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMinimized.onHoverState.IconLeftImage = null;
            this.bunifuButtonMinimized.onHoverState.IconRightImage = null;
            this.bunifuButtonMinimized.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMinimized.OnIdleState.BorderRadius = 1;
            this.bunifuButtonMinimized.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMinimized.OnIdleState.BorderThickness = 1;
            this.bunifuButtonMinimized.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMinimized.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMinimized.OnIdleState.IconLeftImage = null;
            this.bunifuButtonMinimized.OnIdleState.IconRightImage = global::Practice.Properties.Resources.minimise_32px;
            this.bunifuButtonMinimized.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(102)))), ((int)(((byte)(204)))));
            this.bunifuButtonMinimized.OnPressedState.BorderRadius = 1;
            this.bunifuButtonMinimized.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMinimized.OnPressedState.BorderThickness = 1;
            this.bunifuButtonMinimized.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(102)))), ((int)(((byte)(204)))));
            this.bunifuButtonMinimized.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMinimized.OnPressedState.IconLeftImage = null;
            this.bunifuButtonMinimized.OnPressedState.IconRightImage = null;
            this.bunifuButtonMinimized.Size = new System.Drawing.Size(33, 40);
            this.bunifuButtonMinimized.TabIndex = 31;
            this.bunifuButtonMinimized.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonMinimized.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonMinimized.TextMarginLeft = 0;
            this.bunifuButtonMinimized.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonMinimized, "Згорнути програму");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonMinimized, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonMinimized, "");
            this.bunifuButtonMinimized.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButtonClose
            // 
            this.bunifuButtonClose.AllowAnimations = true;
            this.bunifuButtonClose.AllowMouseEffects = true;
            this.bunifuButtonClose.AllowToggling = false;
            this.bunifuButtonClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButtonClose.AnimationSpeed = 200;
            this.bunifuButtonClose.AutoGenerateColors = false;
            this.bunifuButtonClose.AutoRoundBorders = false;
            this.bunifuButtonClose.AutoSizeLeftIcon = true;
            this.bunifuButtonClose.AutoSizeRightIcon = true;
            this.bunifuButtonClose.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonClose.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButtonClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonClose.BackgroundImage")));
            this.bunifuButtonClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.ButtonText = "";
            this.bunifuButtonClose.ButtonTextMarginLeft = 0;
            this.bunifuButtonClose.ColorContrastOnClick = 45;
            this.bunifuButtonClose.ColorContrastOnHover = 45;
            this.bunifuButtonClose.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButtonClose.CustomizableEdges = borderEdges3;
            this.bunifuButtonClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonClose.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButtonClose.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButtonClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonClose.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButtonClose.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonClose.IconLeft = null;
            this.bunifuButtonClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonClose.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonClose.IconMarginLeft = 11;
            this.bunifuButtonClose.IconPadding = 10;
            this.bunifuButtonClose.IconRight = global::Practice.Properties.Resources.Close_32px;
            this.bunifuButtonClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonClose.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonClose.IconSize = 26;
            this.bunifuButtonClose.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButtonClose.IdleBorderRadius = 0;
            this.bunifuButtonClose.IdleBorderThickness = 0;
            this.bunifuButtonClose.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButtonClose.IdleIconLeftImage = null;
            this.bunifuButtonClose.IdleIconRightImage = global::Practice.Properties.Resources.Close_32px;
            this.bunifuButtonClose.IndicateFocus = true;
            this.bunifuButtonClose.Location = new System.Drawing.Point(860, 0);
            this.bunifuButtonClose.Name = "bunifuButtonClose";
            this.bunifuButtonClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonClose.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonClose.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonClose.OnDisabledState.IconRightImage = null;
            this.bunifuButtonClose.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.bunifuButtonClose.onHoverState.BorderRadius = 1;
            this.bunifuButtonClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.onHoverState.BorderThickness = 1;
            this.bunifuButtonClose.onHoverState.FillColor = System.Drawing.Color.Red;
            this.bunifuButtonClose.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonClose.onHoverState.IconLeftImage = null;
            this.bunifuButtonClose.onHoverState.IconRightImage = null;
            this.bunifuButtonClose.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonClose.OnIdleState.BorderRadius = 1;
            this.bunifuButtonClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.OnIdleState.BorderThickness = 1;
            this.bunifuButtonClose.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonClose.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonClose.OnIdleState.IconLeftImage = null;
            this.bunifuButtonClose.OnIdleState.IconRightImage = global::Practice.Properties.Resources.Close_32px;
            this.bunifuButtonClose.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(0)))), ((int)(((byte)(51)))));
            this.bunifuButtonClose.OnPressedState.BorderRadius = 1;
            this.bunifuButtonClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.OnPressedState.BorderThickness = 1;
            this.bunifuButtonClose.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(0)))), ((int)(((byte)(51)))));
            this.bunifuButtonClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonClose.OnPressedState.IconLeftImage = null;
            this.bunifuButtonClose.OnPressedState.IconRightImage = null;
            this.bunifuButtonClose.Size = new System.Drawing.Size(33, 40);
            this.bunifuButtonClose.TabIndex = 30;
            this.bunifuButtonClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonClose.TextMarginLeft = 0;
            this.bunifuButtonClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonClose, "Вийти з програми");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonClose, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonClose, "");
            this.bunifuButtonClose.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuGradientPanelMenu
            // 
            this.bunifuGradientPanelMenu.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanelMenu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanelMenu.BackgroundImage")));
            this.bunifuGradientPanelMenu.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanelMenu.BorderRadius = 0;
            this.bunifuGradientPanelMenu.Controls.Add(this.panelLogo);
            this.bunifuGradientPanelMenu.Controls.Add(this.bunifuButtonTaskOne);
            this.bunifuGradientPanelMenu.Controls.Add(this.bunifuButtonTaskFive);
            this.bunifuGradientPanelMenu.Controls.Add(this.bunifuButtonTaskTwo);
            this.bunifuGradientPanelMenu.Controls.Add(this.bunifuButtonTaskFour);
            this.bunifuGradientPanelMenu.Controls.Add(this.bunifuButtonTaskThree);
            this.bunifuGradientPanelMenu.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuGradientPanelMenu.GradientBottomLeft = System.Drawing.Color.Yellow;
            this.bunifuGradientPanelMenu.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.bunifuGradientPanelMenu.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.bunifuGradientPanelMenu.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.bunifuGradientPanelMenu.Location = new System.Drawing.Point(2, 2);
            this.bunifuGradientPanelMenu.Name = "bunifuGradientPanelMenu";
            this.bunifuGradientPanelMenu.Quality = 10;
            this.bunifuGradientPanelMenu.Size = new System.Drawing.Size(220, 615);
            this.bunifuGradientPanelMenu.TabIndex = 4;
            this.bunifuToolTip.SetToolTip(this.bunifuGradientPanelMenu, "");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuGradientPanelMenu, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuGradientPanelMenu, "");
            // 
            // panelLogo
            // 
            this.panelLogo.Controls.Add(this.bunifuButtonMenu);
            this.panelLogo.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelLogo.Location = new System.Drawing.Point(0, 0);
            this.panelLogo.Name = "panelLogo";
            this.panelLogo.Padding = new System.Windows.Forms.Padding(0, 10, 0, 10);
            this.panelLogo.Size = new System.Drawing.Size(220, 75);
            this.panelLogo.TabIndex = 6;
            this.bunifuToolTip.SetToolTip(this.panelLogo, "");
            this.bunifuToolTip.SetToolTipIcon(this.panelLogo, null);
            this.bunifuToolTip.SetToolTipTitle(this.panelLogo, "");
            // 
            // bunifuButtonMenu
            // 
            this.bunifuButtonMenu.AllowAnimations = true;
            this.bunifuButtonMenu.AllowMouseEffects = true;
            this.bunifuButtonMenu.AllowToggling = false;
            this.bunifuButtonMenu.AnimationSpeed = 200;
            this.bunifuButtonMenu.AutoGenerateColors = false;
            this.bunifuButtonMenu.AutoRoundBorders = false;
            this.bunifuButtonMenu.AutoSizeLeftIcon = true;
            this.bunifuButtonMenu.AutoSizeRightIcon = true;
            this.bunifuButtonMenu.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMenu.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonMenu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonMenu.BackgroundImage")));
            this.bunifuButtonMenu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonMenu.ButtonText = "Меню";
            this.bunifuButtonMenu.ButtonTextMarginLeft = 0;
            this.bunifuButtonMenu.ColorContrastOnClick = 45;
            this.bunifuButtonMenu.ColorContrastOnHover = 45;
            this.bunifuButtonMenu.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButtonMenu.CustomizableEdges = borderEdges4;
            this.bunifuButtonMenu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonMenu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMenu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMenu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMenu.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuButtonMenu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButtonMenu.Font = new System.Drawing.Font("Times New Roman", 14.25F);
            this.bunifuButtonMenu.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMenu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonMenu.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonMenu.IconLeftPadding = new System.Windows.Forms.Padding(10, 3, 3, 3);
            this.bunifuButtonMenu.IconMarginLeft = 11;
            this.bunifuButtonMenu.IconPadding = 10;
            this.bunifuButtonMenu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonMenu.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonMenu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonMenu.IconSize = 25;
            this.bunifuButtonMenu.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonMenu.IdleBorderRadius = 1;
            this.bunifuButtonMenu.IdleBorderThickness = 3;
            this.bunifuButtonMenu.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonMenu.IdleIconLeftImage = global::Practice.Properties.Resources.Hamburger_Menu_64px;
            this.bunifuButtonMenu.IdleIconRightImage = null;
            this.bunifuButtonMenu.IndicateFocus = false;
            this.bunifuButtonMenu.Location = new System.Drawing.Point(0, 10);
            this.bunifuButtonMenu.Name = "bunifuButtonMenu";
            this.bunifuButtonMenu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMenu.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonMenu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonMenu.OnDisabledState.BorderThickness = 3;
            this.bunifuButtonMenu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMenu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMenu.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonMenu.OnDisabledState.IconRightImage = null;
            this.bunifuButtonMenu.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMenu.onHoverState.BorderRadius = 1;
            this.bunifuButtonMenu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonMenu.onHoverState.BorderThickness = 3;
            this.bunifuButtonMenu.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMenu.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMenu.onHoverState.IconLeftImage = null;
            this.bunifuButtonMenu.onHoverState.IconRightImage = null;
            this.bunifuButtonMenu.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonMenu.OnIdleState.BorderRadius = 1;
            this.bunifuButtonMenu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonMenu.OnIdleState.BorderThickness = 3;
            this.bunifuButtonMenu.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonMenu.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMenu.OnIdleState.IconLeftImage = global::Practice.Properties.Resources.Hamburger_Menu_64px;
            this.bunifuButtonMenu.OnIdleState.IconRightImage = null;
            this.bunifuButtonMenu.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMenu.OnPressedState.BorderRadius = 1;
            this.bunifuButtonMenu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonMenu.OnPressedState.BorderThickness = 3;
            this.bunifuButtonMenu.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMenu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMenu.OnPressedState.IconLeftImage = null;
            this.bunifuButtonMenu.OnPressedState.IconRightImage = null;
            this.bunifuButtonMenu.Size = new System.Drawing.Size(220, 55);
            this.bunifuButtonMenu.TabIndex = 29;
            this.bunifuButtonMenu.Tag = "Меню";
            this.bunifuButtonMenu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonMenu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonMenu.TextMarginLeft = 0;
            this.bunifuButtonMenu.TextPadding = new System.Windows.Forms.Padding(7, 0, 0, 0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonMenu, "Меню програми");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonMenu, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonMenu, "");
            this.bunifuButtonMenu.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButtonTaskOne
            // 
            this.bunifuButtonTaskOne.AllowAnimations = true;
            this.bunifuButtonTaskOne.AllowMouseEffects = true;
            this.bunifuButtonTaskOne.AllowToggling = false;
            this.bunifuButtonTaskOne.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButtonTaskOne.AnimationSpeed = 200;
            this.bunifuButtonTaskOne.AutoGenerateColors = false;
            this.bunifuButtonTaskOne.AutoRoundBorders = false;
            this.bunifuButtonTaskOne.AutoSizeLeftIcon = true;
            this.bunifuButtonTaskOne.AutoSizeRightIcon = true;
            this.bunifuButtonTaskOne.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonTaskOne.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskOne.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonTaskOne.BackgroundImage")));
            this.bunifuButtonTaskOne.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskOne.ButtonText = "Завдання №1";
            this.bunifuButtonTaskOne.ButtonTextMarginLeft = 0;
            this.bunifuButtonTaskOne.ColorContrastOnClick = 45;
            this.bunifuButtonTaskOne.ColorContrastOnHover = 45;
            this.bunifuButtonTaskOne.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButtonTaskOne.CustomizableEdges = borderEdges5;
            this.bunifuButtonTaskOne.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonTaskOne.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonTaskOne.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonTaskOne.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonTaskOne.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.bunifuButtonTaskOne.Font = new System.Drawing.Font("Times New Roman", 14.25F);
            this.bunifuButtonTaskOne.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskOne.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonTaskOne.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonTaskOne.IconLeftPadding = new System.Windows.Forms.Padding(5, 3, 3, 3);
            this.bunifuButtonTaskOne.IconMarginLeft = 11;
            this.bunifuButtonTaskOne.IconPadding = 10;
            this.bunifuButtonTaskOne.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonTaskOne.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonTaskOne.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonTaskOne.IconSize = 30;
            this.bunifuButtonTaskOne.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskOne.IdleBorderRadius = 1;
            this.bunifuButtonTaskOne.IdleBorderThickness = 3;
            this.bunifuButtonTaskOne.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskOne.IdleIconLeftImage = global::Practice.Properties.Resources._1_100px;
            this.bunifuButtonTaskOne.IdleIconRightImage = null;
            this.bunifuButtonTaskOne.IndicateFocus = false;
            this.bunifuButtonTaskOne.Location = new System.Drawing.Point(0, 75);
            this.bunifuButtonTaskOne.Name = "bunifuButtonTaskOne";
            this.bunifuButtonTaskOne.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonTaskOne.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonTaskOne.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskOne.OnDisabledState.BorderThickness = 3;
            this.bunifuButtonTaskOne.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonTaskOne.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonTaskOne.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonTaskOne.OnDisabledState.IconRightImage = null;
            this.bunifuButtonTaskOne.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonTaskOne.onHoverState.BorderRadius = 1;
            this.bunifuButtonTaskOne.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskOne.onHoverState.BorderThickness = 3;
            this.bunifuButtonTaskOne.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonTaskOne.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskOne.onHoverState.IconLeftImage = null;
            this.bunifuButtonTaskOne.onHoverState.IconRightImage = null;
            this.bunifuButtonTaskOne.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskOne.OnIdleState.BorderRadius = 1;
            this.bunifuButtonTaskOne.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskOne.OnIdleState.BorderThickness = 3;
            this.bunifuButtonTaskOne.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskOne.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskOne.OnIdleState.IconLeftImage = global::Practice.Properties.Resources._1_100px;
            this.bunifuButtonTaskOne.OnIdleState.IconRightImage = null;
            this.bunifuButtonTaskOne.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonTaskOne.OnPressedState.BorderRadius = 1;
            this.bunifuButtonTaskOne.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskOne.OnPressedState.BorderThickness = 3;
            this.bunifuButtonTaskOne.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonTaskOne.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskOne.OnPressedState.IconLeftImage = null;
            this.bunifuButtonTaskOne.OnPressedState.IconRightImage = null;
            this.bunifuButtonTaskOne.Size = new System.Drawing.Size(220, 70);
            this.bunifuButtonTaskOne.TabIndex = 23;
            this.bunifuButtonTaskOne.Tag = "Завдання №1";
            this.bunifuButtonTaskOne.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonTaskOne.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonTaskOne.TextMarginLeft = 0;
            this.bunifuButtonTaskOne.TextPadding = new System.Windows.Forms.Padding(7, 0, 0, 0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonTaskOne, "Завдання №1");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonTaskOne, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonTaskOne, "");
            this.bunifuButtonTaskOne.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButtonTaskFive
            // 
            this.bunifuButtonTaskFive.AllowAnimations = true;
            this.bunifuButtonTaskFive.AllowMouseEffects = true;
            this.bunifuButtonTaskFive.AllowToggling = false;
            this.bunifuButtonTaskFive.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButtonTaskFive.AnimationSpeed = 200;
            this.bunifuButtonTaskFive.AutoGenerateColors = false;
            this.bunifuButtonTaskFive.AutoRoundBorders = false;
            this.bunifuButtonTaskFive.AutoSizeLeftIcon = true;
            this.bunifuButtonTaskFive.AutoSizeRightIcon = true;
            this.bunifuButtonTaskFive.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonTaskFive.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskFive.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonTaskFive.BackgroundImage")));
            this.bunifuButtonTaskFive.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskFive.ButtonText = "Завдання №5";
            this.bunifuButtonTaskFive.ButtonTextMarginLeft = 0;
            this.bunifuButtonTaskFive.ColorContrastOnClick = 45;
            this.bunifuButtonTaskFive.ColorContrastOnHover = 45;
            this.bunifuButtonTaskFive.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButtonTaskFive.CustomizableEdges = borderEdges6;
            this.bunifuButtonTaskFive.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonTaskFive.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonTaskFive.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonTaskFive.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonTaskFive.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButtonTaskFive.Font = new System.Drawing.Font("Times New Roman", 14.25F);
            this.bunifuButtonTaskFive.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskFive.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonTaskFive.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonTaskFive.IconLeftPadding = new System.Windows.Forms.Padding(5, 3, 3, 3);
            this.bunifuButtonTaskFive.IconMarginLeft = 11;
            this.bunifuButtonTaskFive.IconPadding = 10;
            this.bunifuButtonTaskFive.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonTaskFive.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonTaskFive.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonTaskFive.IconSize = 30;
            this.bunifuButtonTaskFive.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskFive.IdleBorderRadius = 1;
            this.bunifuButtonTaskFive.IdleBorderThickness = 3;
            this.bunifuButtonTaskFive.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskFive.IdleIconLeftImage = global::Practice.Properties.Resources._5_100px;
            this.bunifuButtonTaskFive.IdleIconRightImage = null;
            this.bunifuButtonTaskFive.IndicateFocus = true;
            this.bunifuButtonTaskFive.Location = new System.Drawing.Point(0, 355);
            this.bunifuButtonTaskFive.Name = "bunifuButtonTaskFive";
            this.bunifuButtonTaskFive.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonTaskFive.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonTaskFive.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskFive.OnDisabledState.BorderThickness = 3;
            this.bunifuButtonTaskFive.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonTaskFive.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonTaskFive.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonTaskFive.OnDisabledState.IconRightImage = null;
            this.bunifuButtonTaskFive.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonTaskFive.onHoverState.BorderRadius = 1;
            this.bunifuButtonTaskFive.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskFive.onHoverState.BorderThickness = 3;
            this.bunifuButtonTaskFive.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonTaskFive.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskFive.onHoverState.IconLeftImage = null;
            this.bunifuButtonTaskFive.onHoverState.IconRightImage = null;
            this.bunifuButtonTaskFive.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskFive.OnIdleState.BorderRadius = 1;
            this.bunifuButtonTaskFive.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskFive.OnIdleState.BorderThickness = 3;
            this.bunifuButtonTaskFive.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskFive.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskFive.OnIdleState.IconLeftImage = global::Practice.Properties.Resources._5_100px;
            this.bunifuButtonTaskFive.OnIdleState.IconRightImage = null;
            this.bunifuButtonTaskFive.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonTaskFive.OnPressedState.BorderRadius = 1;
            this.bunifuButtonTaskFive.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskFive.OnPressedState.BorderThickness = 3;
            this.bunifuButtonTaskFive.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonTaskFive.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskFive.OnPressedState.IconLeftImage = null;
            this.bunifuButtonTaskFive.OnPressedState.IconRightImage = null;
            this.bunifuButtonTaskFive.Size = new System.Drawing.Size(220, 70);
            this.bunifuButtonTaskFive.TabIndex = 27;
            this.bunifuButtonTaskFive.Tag = "Завдання №5";
            this.bunifuButtonTaskFive.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonTaskFive.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonTaskFive.TextMarginLeft = 0;
            this.bunifuButtonTaskFive.TextPadding = new System.Windows.Forms.Padding(7, 0, 0, 0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonTaskFive, "Завдання №5");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonTaskFive, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonTaskFive, "");
            this.bunifuButtonTaskFive.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonTaskFive.Click += new System.EventHandler(this.TaskFive_Click);
            // 
            // bunifuButtonTaskTwo
            // 
            this.bunifuButtonTaskTwo.AllowAnimations = true;
            this.bunifuButtonTaskTwo.AllowMouseEffects = true;
            this.bunifuButtonTaskTwo.AllowToggling = false;
            this.bunifuButtonTaskTwo.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButtonTaskTwo.AnimationSpeed = 200;
            this.bunifuButtonTaskTwo.AutoGenerateColors = false;
            this.bunifuButtonTaskTwo.AutoRoundBorders = false;
            this.bunifuButtonTaskTwo.AutoSizeLeftIcon = true;
            this.bunifuButtonTaskTwo.AutoSizeRightIcon = true;
            this.bunifuButtonTaskTwo.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonTaskTwo.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskTwo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonTaskTwo.BackgroundImage")));
            this.bunifuButtonTaskTwo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskTwo.ButtonText = "Завдання №2";
            this.bunifuButtonTaskTwo.ButtonTextMarginLeft = 0;
            this.bunifuButtonTaskTwo.ColorContrastOnClick = 45;
            this.bunifuButtonTaskTwo.ColorContrastOnHover = 45;
            this.bunifuButtonTaskTwo.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bunifuButtonTaskTwo.CustomizableEdges = borderEdges7;
            this.bunifuButtonTaskTwo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonTaskTwo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonTaskTwo.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonTaskTwo.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonTaskTwo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.bunifuButtonTaskTwo.Font = new System.Drawing.Font("Times New Roman", 14.25F);
            this.bunifuButtonTaskTwo.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskTwo.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonTaskTwo.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonTaskTwo.IconLeftPadding = new System.Windows.Forms.Padding(5, 3, 3, 3);
            this.bunifuButtonTaskTwo.IconMarginLeft = 11;
            this.bunifuButtonTaskTwo.IconPadding = 10;
            this.bunifuButtonTaskTwo.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonTaskTwo.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonTaskTwo.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonTaskTwo.IconSize = 30;
            this.bunifuButtonTaskTwo.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskTwo.IdleBorderRadius = 1;
            this.bunifuButtonTaskTwo.IdleBorderThickness = 3;
            this.bunifuButtonTaskTwo.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskTwo.IdleIconLeftImage = global::Practice.Properties.Resources._2_100px;
            this.bunifuButtonTaskTwo.IdleIconRightImage = null;
            this.bunifuButtonTaskTwo.IndicateFocus = false;
            this.bunifuButtonTaskTwo.Location = new System.Drawing.Point(0, 145);
            this.bunifuButtonTaskTwo.Name = "bunifuButtonTaskTwo";
            this.bunifuButtonTaskTwo.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonTaskTwo.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonTaskTwo.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskTwo.OnDisabledState.BorderThickness = 3;
            this.bunifuButtonTaskTwo.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonTaskTwo.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonTaskTwo.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonTaskTwo.OnDisabledState.IconRightImage = null;
            this.bunifuButtonTaskTwo.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonTaskTwo.onHoverState.BorderRadius = 1;
            this.bunifuButtonTaskTwo.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskTwo.onHoverState.BorderThickness = 3;
            this.bunifuButtonTaskTwo.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonTaskTwo.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskTwo.onHoverState.IconLeftImage = null;
            this.bunifuButtonTaskTwo.onHoverState.IconRightImage = null;
            this.bunifuButtonTaskTwo.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskTwo.OnIdleState.BorderRadius = 1;
            this.bunifuButtonTaskTwo.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskTwo.OnIdleState.BorderThickness = 3;
            this.bunifuButtonTaskTwo.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskTwo.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskTwo.OnIdleState.IconLeftImage = global::Practice.Properties.Resources._2_100px;
            this.bunifuButtonTaskTwo.OnIdleState.IconRightImage = null;
            this.bunifuButtonTaskTwo.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonTaskTwo.OnPressedState.BorderRadius = 1;
            this.bunifuButtonTaskTwo.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskTwo.OnPressedState.BorderThickness = 3;
            this.bunifuButtonTaskTwo.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonTaskTwo.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskTwo.OnPressedState.IconLeftImage = null;
            this.bunifuButtonTaskTwo.OnPressedState.IconRightImage = null;
            this.bunifuButtonTaskTwo.Size = new System.Drawing.Size(220, 70);
            this.bunifuButtonTaskTwo.TabIndex = 24;
            this.bunifuButtonTaskTwo.Tag = "Завдання №2";
            this.bunifuButtonTaskTwo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonTaskTwo.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonTaskTwo.TextMarginLeft = 0;
            this.bunifuButtonTaskTwo.TextPadding = new System.Windows.Forms.Padding(7, 0, 0, 0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonTaskTwo, "Завдання №2");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonTaskTwo, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonTaskTwo, "");
            this.bunifuButtonTaskTwo.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonTaskTwo.Click += new System.EventHandler(this.TaskTwo_Click);
            // 
            // bunifuButtonTaskFour
            // 
            this.bunifuButtonTaskFour.AllowAnimations = true;
            this.bunifuButtonTaskFour.AllowMouseEffects = true;
            this.bunifuButtonTaskFour.AllowToggling = false;
            this.bunifuButtonTaskFour.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButtonTaskFour.AnimationSpeed = 200;
            this.bunifuButtonTaskFour.AutoGenerateColors = false;
            this.bunifuButtonTaskFour.AutoRoundBorders = false;
            this.bunifuButtonTaskFour.AutoSizeLeftIcon = true;
            this.bunifuButtonTaskFour.AutoSizeRightIcon = true;
            this.bunifuButtonTaskFour.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonTaskFour.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskFour.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonTaskFour.BackgroundImage")));
            this.bunifuButtonTaskFour.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskFour.ButtonText = "Завдання №4";
            this.bunifuButtonTaskFour.ButtonTextMarginLeft = 0;
            this.bunifuButtonTaskFour.ColorContrastOnClick = 45;
            this.bunifuButtonTaskFour.ColorContrastOnHover = 45;
            this.bunifuButtonTaskFour.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButtonTaskFour.CustomizableEdges = borderEdges8;
            this.bunifuButtonTaskFour.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonTaskFour.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonTaskFour.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonTaskFour.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonTaskFour.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.bunifuButtonTaskFour.Font = new System.Drawing.Font("Times New Roman", 14.25F);
            this.bunifuButtonTaskFour.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskFour.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonTaskFour.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonTaskFour.IconLeftPadding = new System.Windows.Forms.Padding(5, 3, 3, 3);
            this.bunifuButtonTaskFour.IconMarginLeft = 11;
            this.bunifuButtonTaskFour.IconPadding = 10;
            this.bunifuButtonTaskFour.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonTaskFour.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonTaskFour.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonTaskFour.IconSize = 30;
            this.bunifuButtonTaskFour.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskFour.IdleBorderRadius = 1;
            this.bunifuButtonTaskFour.IdleBorderThickness = 3;
            this.bunifuButtonTaskFour.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskFour.IdleIconLeftImage = global::Practice.Properties.Resources._4_100px;
            this.bunifuButtonTaskFour.IdleIconRightImage = null;
            this.bunifuButtonTaskFour.IndicateFocus = false;
            this.bunifuButtonTaskFour.Location = new System.Drawing.Point(0, 285);
            this.bunifuButtonTaskFour.Name = "bunifuButtonTaskFour";
            this.bunifuButtonTaskFour.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonTaskFour.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonTaskFour.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskFour.OnDisabledState.BorderThickness = 3;
            this.bunifuButtonTaskFour.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonTaskFour.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonTaskFour.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonTaskFour.OnDisabledState.IconRightImage = null;
            this.bunifuButtonTaskFour.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonTaskFour.onHoverState.BorderRadius = 1;
            this.bunifuButtonTaskFour.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskFour.onHoverState.BorderThickness = 3;
            this.bunifuButtonTaskFour.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonTaskFour.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskFour.onHoverState.IconLeftImage = null;
            this.bunifuButtonTaskFour.onHoverState.IconRightImage = null;
            this.bunifuButtonTaskFour.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskFour.OnIdleState.BorderRadius = 1;
            this.bunifuButtonTaskFour.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskFour.OnIdleState.BorderThickness = 3;
            this.bunifuButtonTaskFour.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskFour.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskFour.OnIdleState.IconLeftImage = global::Practice.Properties.Resources._4_100px;
            this.bunifuButtonTaskFour.OnIdleState.IconRightImage = null;
            this.bunifuButtonTaskFour.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonTaskFour.OnPressedState.BorderRadius = 1;
            this.bunifuButtonTaskFour.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskFour.OnPressedState.BorderThickness = 3;
            this.bunifuButtonTaskFour.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonTaskFour.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskFour.OnPressedState.IconLeftImage = null;
            this.bunifuButtonTaskFour.OnPressedState.IconRightImage = null;
            this.bunifuButtonTaskFour.Size = new System.Drawing.Size(220, 70);
            this.bunifuButtonTaskFour.TabIndex = 26;
            this.bunifuButtonTaskFour.Tag = "Завдання №4";
            this.bunifuButtonTaskFour.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonTaskFour.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonTaskFour.TextMarginLeft = 0;
            this.bunifuButtonTaskFour.TextPadding = new System.Windows.Forms.Padding(7, 0, 0, 0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonTaskFour, "Завдання №4");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonTaskFour, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonTaskFour, "");
            this.bunifuButtonTaskFour.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonTaskFour.Click += new System.EventHandler(this.TaskFour_Click);
            // 
            // bunifuButtonTaskThree
            // 
            this.bunifuButtonTaskThree.AllowAnimations = true;
            this.bunifuButtonTaskThree.AllowMouseEffects = true;
            this.bunifuButtonTaskThree.AllowToggling = false;
            this.bunifuButtonTaskThree.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButtonTaskThree.AnimationSpeed = 200;
            this.bunifuButtonTaskThree.AutoGenerateColors = false;
            this.bunifuButtonTaskThree.AutoRoundBorders = false;
            this.bunifuButtonTaskThree.AutoSizeLeftIcon = true;
            this.bunifuButtonTaskThree.AutoSizeRightIcon = true;
            this.bunifuButtonTaskThree.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonTaskThree.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskThree.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonTaskThree.BackgroundImage")));
            this.bunifuButtonTaskThree.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskThree.ButtonText = "Завдання №3";
            this.bunifuButtonTaskThree.ButtonTextMarginLeft = 0;
            this.bunifuButtonTaskThree.ColorContrastOnClick = 45;
            this.bunifuButtonTaskThree.ColorContrastOnHover = 45;
            this.bunifuButtonTaskThree.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.bunifuButtonTaskThree.CustomizableEdges = borderEdges9;
            this.bunifuButtonTaskThree.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonTaskThree.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonTaskThree.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonTaskThree.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonTaskThree.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButtonTaskThree.Font = new System.Drawing.Font("Times New Roman", 14.25F);
            this.bunifuButtonTaskThree.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskThree.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonTaskThree.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonTaskThree.IconLeftPadding = new System.Windows.Forms.Padding(5, 3, 3, 3);
            this.bunifuButtonTaskThree.IconMarginLeft = 11;
            this.bunifuButtonTaskThree.IconPadding = 10;
            this.bunifuButtonTaskThree.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonTaskThree.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonTaskThree.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonTaskThree.IconSize = 30;
            this.bunifuButtonTaskThree.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskThree.IdleBorderRadius = 1;
            this.bunifuButtonTaskThree.IdleBorderThickness = 3;
            this.bunifuButtonTaskThree.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskThree.IdleIconLeftImage = global::Practice.Properties.Resources._3_100px;
            this.bunifuButtonTaskThree.IdleIconRightImage = null;
            this.bunifuButtonTaskThree.IndicateFocus = false;
            this.bunifuButtonTaskThree.Location = new System.Drawing.Point(0, 215);
            this.bunifuButtonTaskThree.Name = "bunifuButtonTaskThree";
            this.bunifuButtonTaskThree.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonTaskThree.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonTaskThree.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskThree.OnDisabledState.BorderThickness = 3;
            this.bunifuButtonTaskThree.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonTaskThree.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonTaskThree.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonTaskThree.OnDisabledState.IconRightImage = null;
            this.bunifuButtonTaskThree.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonTaskThree.onHoverState.BorderRadius = 1;
            this.bunifuButtonTaskThree.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskThree.onHoverState.BorderThickness = 3;
            this.bunifuButtonTaskThree.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonTaskThree.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskThree.onHoverState.IconLeftImage = null;
            this.bunifuButtonTaskThree.onHoverState.IconRightImage = null;
            this.bunifuButtonTaskThree.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskThree.OnIdleState.BorderRadius = 1;
            this.bunifuButtonTaskThree.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskThree.OnIdleState.BorderThickness = 3;
            this.bunifuButtonTaskThree.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(153)))), ((int)(((byte)(102)))));
            this.bunifuButtonTaskThree.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskThree.OnIdleState.IconLeftImage = global::Practice.Properties.Resources._3_100px;
            this.bunifuButtonTaskThree.OnIdleState.IconRightImage = null;
            this.bunifuButtonTaskThree.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonTaskThree.OnPressedState.BorderRadius = 1;
            this.bunifuButtonTaskThree.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonTaskThree.OnPressedState.BorderThickness = 3;
            this.bunifuButtonTaskThree.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonTaskThree.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTaskThree.OnPressedState.IconLeftImage = null;
            this.bunifuButtonTaskThree.OnPressedState.IconRightImage = null;
            this.bunifuButtonTaskThree.Size = new System.Drawing.Size(220, 70);
            this.bunifuButtonTaskThree.TabIndex = 25;
            this.bunifuButtonTaskThree.Tag = "Завдання №3";
            this.bunifuButtonTaskThree.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonTaskThree.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonTaskThree.TextMarginLeft = 0;
            this.bunifuButtonTaskThree.TextPadding = new System.Windows.Forms.Padding(7, 0, 0, 0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonTaskThree, "Завдання №3");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonTaskThree, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonTaskThree, "");
            this.bunifuButtonTaskThree.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonTaskThree.Click += new System.EventHandler(this.TaskThree_Click);
            // 
            // UserProfile
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1117, 619);
            this.Controls.Add(this.bunifuGradientPanelDesktop);
            this.Controls.Add(this.bunifuGradientPanelTitleBar);
            this.Controls.Add(this.bunifuGradientPanelMenu);
            this.DoubleBuffered = true;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.MinimumSize = new System.Drawing.Size(520, 425);
            this.Name = "UserProfile";
            this.Padding = new System.Windows.Forms.Padding(2);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Tag = "";
            this.bunifuGradientPanelTitleBar.ResumeLayout(false);
            this.bunifuGradientPanelTitleBar.PerformLayout();
            this.bunifuGradientPanelMenu.ResumeLayout(false);
            this.panelLogo.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Label labelCurrentChildForm;
        private Bunifu.UI.WinForms.BunifuFormDock formDock;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonClose;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonMaximize;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonMinimized;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonTaskOne;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonTaskFive;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonTaskFour;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonTaskThree;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonTaskTwo;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanelMenu;
        private System.Windows.Forms.Panel panelLogo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonMenu;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanelTitleBar;
        private Bunifu.UI.WinForms.BunifuImageButton iconCurrentChildForm;
        private Bunifu.UI.WinForms.BunifuToolTip bunifuToolTip;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanelDesktop;
    }
}

